version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - votipian-network

  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: votipian-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/votipian
      - JWT_SECRET=your_jwt_secret_key
      - NODE_ENV=development
    depends_on:
      - mongodb
    networks:
      - votipian-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: votipian-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - votipian-network

networks:
  votipian-network:
    driver: bridge

volumes:
  mongodb_data:
