services:
  - type: web
    name: votipian-server
    env: node
    region: singapore
    plan: free
    buildCommand: |
      npm install
      npm run build:server
    startCommand: |
      cd server
      node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: CLIENT_URL
        value: https://votipian-client.onrender.com

  - type: web
    name: votipian-client
    env: node
    region: singapore
    plan: free
    buildCommand: |
      npm install
      npm run build:client
    startCommand: |
      cd client
      npx serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: https://votipian-server.onrender.com
